mullvad/windows-service-rs

- appveyor.yml
To prevent dropping support for an older version of Rust without even noticing it it's good to always run tests towards the oldest supported version. This way one can easily see when compatibility is broken.
It's nothing wrong with bumping the minimum required version. But it should then also bump the major version number in the crate, so peoples builds don't start breaking randomly. And it should also be added to the changelog I think.
Funny enough our oldest supported version at the moment seems to be 1.26, which is the newest stable version. See these build logs for the errors on 1.25 for example: https://ci.appveyor.com/project/Mullvad/windows-service-rs/build/1.0.8/job/l8pq700041thrlvi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Automatic tests on minimum rustc version

- Cargo.toml
- README.md
- examples/install_service.rs
- examples/ping_service.rs
- examples/uninstall_service.rs
- src/lib.rs
- src/service.rs
- src/service_control_handler.rs
- src/service_dispatcher.rs
- src/service_manager.rs
At first I noticed that we had many different error types, and all had the `System(::std::io::Error) #[doc = "System call error."];` variant in it. Many of them also had other overlapping/equal error variants.
`error-chain` itself mandates having one crate-global error that the library exports. We have previously not followed this because we usually have very different errors in different modules, so it does not make much sense to group them etc. But here I felt they did overlap and it made a lot of sense to have one common `windows_service::Error`.
Then I also wanted to play around with the new functionality that `main` can return a `Result`. So I thought I'll try to incorporate that into the documentation in order to do "proper" error handling in the examples and documentation.
---
This …
> Unify errors and handle errors in examples

- Cargo.toml
Getting error-chain up to speed just like all our other libs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/8)
> Upgrade error-chain to 0.12

- CHANGELOG.md
- src/service.rs
I personally feel that `ServiceExitCode::default()` feels a bit unclear what it means. It can of course be kept, and `NO_ERROR` is probably a very good default. But on top of that I would like to add a safe Rust constant that can be used and where the name is obvious.
So just for the exact same reason Windows defines the constant `NO_ERROR` and one is likely to use `return NO_ERROR` from their C code, it makes the equivalent sense to want to do `return ServiceExitCode::NO_ERROR` in Rust IMO.
Are there other, similar constants defined by Windows that makes sense to expose? Such as `ERROR` being just `1` or something?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-r …
> Add a NO_ERROR const to ServiceExitCode

- src/service.rs
- src/service_dispatcher.rs
- src/service_manager.rs
The error handling routine, when using the `winsvc::` family of functions, makes a false assumption that `1` is the only successful return code.
As per docs the *nonzero* code indicates success, so we should not assume that `1` is the only code returned upon success.
>If the function succeeds, the return value is nonzero.
>If the function fails, the return value is zero. To get extended error information, call GetLastError.
This PR remedies this issue by inversing the conditional check to check for failure first, since `0` is guaranteed to be returned on error. Even though we didn't stumble directly into any errors, it's still better to stick to what docs suggest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix winapi result handling

- README.md
- examples/install_service.rs
- examples/ping_service.rs
- src/lib.rs
- src/service.rs
- src/service_manager.rs
Interactive services on Windows have to pass the additional flag `SERVICE_INTERACTIVE_PROCESS` along with the service type itself during registration. That is said, the service type is a bit mask, so we shall define it as such in Rust too. Apart from that this PR adds all other missing service types.
Reference:
https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/nf-winsvc-createservicea
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/17)
> Convert ServiceType to bitflags and add missing service types

- examples/install_service.rs
- examples/ping_service.rs
- examples/service_config.rs
- examples/uninstall_service.rs
- src/lib.rs
- src/service.rs
- src/service_control_handler.rs
- src/service_dispatcher.rs
- src/service_manager.rs
There were a number of places where we had `.map_err(|_| Error::InvalidFoo)`. Thus mapping an existing error type into another one, discarding the original. This will only tell the user of the library that the `Foo` was invalid, but not why/how. By making sure all of them retain the underlying `NulError` it becomes possible for a user of the library to query the underlying `source` of the error.
Also did some unrelated cleanup in the examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/25)
> Preserve underlying error

- src/lib.rs
- src/service.rs
- src/service_control_handler.rs
- src/service_dispatcher.rs
- src/service_manager.rs
I try again to simplify/clean the error type(s) and make the error handling abstracted on a good and nice level. I'm experimenting a bit, and I'm not 100% sure I have reached the optimal design, but I'm thinking it's starting to be rather nice now.
This PR basically does two things to the errors:
1. Make all `from_raw(u32)` constructors return a unified `TryFromIntError(u32)`. Much like how the standard library implementations of `TryFrom` on integers return one single error type.
I still need to keep two of the previous `from_raw` error variants on the combination `Error` enum. Since those can happen as part of methods with multiple types of errors in them.
Overall I think this is cleaner. On the lower level, constructors like `ServiceStatus::from_raw` no longer return a huge error with …
> Break apart leaf errors

- CHANGELOG.md
- Cargo.toml
We should release an update at some point. I've bumped the version to 0.2.0 because the recent change to `ServiceType` breaks the backward compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/19)
> Bump 0.2.0

- CHANGELOG.md
- Cargo.toml
- examples/service_failure_actions.rs
- src/lib.rs
- src/service.rs
This PR adds service failure actions configuration in the `Service` struct.
- `Service.get_failure_actions() -> Result<ServiceFailureActions>` returns the currently configured failure actions `ServiceFailureActions` struct.
- `Service.update_failure_actions(ServiceFailureActions)`  does incremental update to the failure actions config. Basically almost all of the fields in `ServiceFailureActions` are optional, so passing `None` would leave the corresponding setting unchanged, however passing an empty value would reset it, i.e for strings `Some("")` or for vectors `Some(vec![])`.
- `Service.set_failure_actions_on_non_crash_failures(bool)` - enables failure actions for non-crash failures, i.e if the service exited with non-zero code (not the same as process exit code, but the one passed via …
> Add service failure actions

- Cargo.toml
- examples/ping_service.rs
- src/double_nul_terminated.rs
- src/lib.rs
- src/service.rs
- src/service_control_handler.rs
- src/service_dispatcher.rs
- src/service_manager.rs
I found there were two breaking upgrades to our dependencies. `bitflags` was painless, but `widestrings` had changed their API a bit. Mostly that the error type is now generic over the backing integer type, and that `from_str` is now named `from_os_str` if converting from an `&OsStr`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/34)
> Upgrade dependencies. And adapt to new widestrings API

- Cargo.toml
As suggested by @retep998. Making it so that going to this crate on docs.rs will go directly to the Windows version. Which is the only version that makes sense really.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/35)
> Point docs.rs to the Windows docs by default

- CHANGELOG.md
- Cargo.toml
- appveyor.yml
- src/lib.rs
Upgrade the `err-derive` dependency. Not because we need really, but we had to bump the MSRV anyway, since `err-derive 0.1.6` bumped the `quote` depndency to 1.0 which increased MSRV. Some people don't regard requiring newer Rust as a breaking change. Anyway, when I was at it I upgraded to their breaking change 0.2 as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/36)
> Upgrade err derive

- src/service.rs
As above.
The output from `service_failure_actions.rs` seems to be unchanged. Which makes sense, because there was always a symmetry in how we handled this value.
I've verified the changes by looking at how the services applet in Windows interprets the delay value. With these changes, both our code and the services applet have a mutual understanding of how the value should be interpreted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/37)
> Treat 'ServiceAction' delay field as count of milliseconds

- CHANGELOG.md
- appveyor.yml
- src/service.rs
Make use of `Duration::as_millis()` instead of `as_secs() * 1000` which results in lost precision.
Also convert duration integers to smaller integers with the help of `TryFrom` in order to catch overflows and panic. As said on slack, we might not want to bloat the API with `Result` types. But I felt that silently using a possibly wildly different delay than the given is also bad. So panicking and documenting the panic is the best solution IMO.
People should use this API with mostly hardcoded durations anyway, so they will see they use the wrong delays directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/38)
> Use precise delay duration

- CHANGELOG.md
- examples/install_service.rs
- examples/service_failure_actions.rs
- src/service.rs
- src/service_manager.rs
Previously, for an existing service, you could only configure optional settings. There was no way to configure the mandatory settings for an existing service.
These changes add the required functionality to configure the mandatory settings on an existing service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/40)
> Configure mandatory service settings

- CHANGELOG.md
- examples/pause_continue.rs
- src/service.rs
This PR adds support to pause and continue services using programmatic API.
Since `continue` is a reserved keyword in Rust, I opt-in to use `resume` instead in`Service` interface. Windows Services Pane UI also refers to "continue" as "resume", while programmatic APIs mostly use pause/continue pair, such as in permissons mask -- `PAUSE_CONTINUE`.
Fixes #41
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/42)
> Add support to pause and continue services

- examples/ping_service.rs
- src/lib.rs
- src/service.rs
Uses `QueryServiceStatusEx` to obtain service pid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/44)
> Retrieve pid when querying service status

- Cargo.toml
pr updates err-derive version to latest. fixes build issue on version `0.2.1`  patched at https://gitlab.com/torkleyy/err-derive/-/commit/49464f46e686a51d2d8cb0f210d6cc2785a83f41.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/46)
> update err drive

- Cargo.toml
- src/lib.rs
- src/service.rs
- src/winsvc_vendored.rs
The repo cannot be released at the moment, because we depend on changes to the master branch of [winapi-rs](https://github.com/retep998/winapi-rs) that have not yet been released. So let's include those changes in this repository and depend on the last release of `winapi-rs`.
Fixes issue #43.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/49)
> Vendor in unpublished winapi-rs code

- CHANGELOG.md
- src/service.rs
Current `master` is broken. Functions that query service config seg fault at random:
```
$ RUST_BACKTRACE=1 cargo run --example service_config
Finished dev [unoptimized + debuginfo] target(s) in 0.04s
Running `target\debug\examples\service_config.exe`
error: process didn't exit successfully: `target\debug\examples\service_config.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
Segmentation fault
```
I suspect that the problem is that we pass an 8K buffer allocated on stack into `QueryServiceConfig*` functions, which expect a heap allocated memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/55)
> Fix seg fault when calling to QueryServiceConfig* functions

- CHANGELOG.md
- src/service.rs
- src/service_manager.rs
This PR migrates the rest of the codebase to `impl Trait` in places where we used to have generic parameter. This is a breaking change & should be merged after all other PR have been merged & released as a part of major release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/56)
> Use impl Trait instead of generic parameter

- CHANGELOG.md
- src/service_control_handler.rs
Mark `ServiceStatusHandle` as Sync, per https://github.com/mullvad/windows-service-rs/issues/64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/65)
> Make `ServiceStatusHandle` Sync.

- src/service_control_handler.rs
This is needed for users who want to pass SERVICE_STATUS_HANDLE into
other Windows APIs such as the RegisterPowerSettingNotification API
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerpowersettingnotification
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/69)
> Add API to expose ServiceStatusHandle as_raw_handle

- src/double_nul_terminated.rs
- src/service.rs
- src/service_control_handler.rs
- src/shell_escape.rs
1. Rename `from_vec` to `from_slice` since it takes a slice, not a `Vec`.
2. Allocate `WideString` in `from_slice` with pre-calculated capacity.
3. Add unit tests for `from_slice`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/91)
> Refactor `double_nul_terminated`

- src/service.rs
This function wraps the Win32 API which configures if an auto-start service should be delayed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/88)
> Add `Service.set_delayed_auto_start`

- CHANGELOG.md
- src/service.rs
- This PR adds additional message to panic error by using `Result::expect()` when converting `Duration` to `u32`.
- Update CHANGELOG with the recent addition of pre shutdown timeout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/98)
> Minor adjustments

- examples/uninstall_service.rs
- src/service.rs
The underlying win32 API call merely marks the service for deletion. It can be called even if the service is not stopped and will not invalidate the caller's open handle to it. Making the function not consuming self allows the caller to decide when to close the handle. Docs and examples are updated to show the correct behavior of this API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/90)
> Breaking: change `Service.delete` to borrow rather than consume `self`

- .github/workflows/build-and-test.yml
There's an issue with the `setup-mingw` action for newer versions of mingw: https://github.com/mullvad/windows-service-rs/actions/runs/6889525757/job/18745989633?pr=109
Let's use an older version of mingw until that has been fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/110)
> Pin mingw version in workflow

- Cargo.toml
`windows-sys` moved its MSRV to 1.56, which is less or equal to the one in this crate since the
edition for `windows-service` is 2021, so no impact there.
Could we have a release after this is merged ? ~~I don't see any `pub use` of `windows_sys::` stuff
so a point release should be enough.~~ `windows-sys` is part of the public API so it would need a breaking release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/109)
> deps: update to windows-sys 0.52.0

- CHANGELOG.md
- examples/notify_service.rs
- examples/ping_service.rs
- src/service.rs
Minor addition, no breaking changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/108)
> Add support for user-defined control codes

- CHANGELOG.md
- src/service.rs
Extend `PowerBroadcastSetting` to handle `LidSwitchStateChange` events.
Documentation for [Power Setting GUIDs](https://learn.microsoft.com/en-us/windows/win32/power/power-setting-guids).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/111)
> Add support for `LidSwitchStateChange` in `PowerBroadcastSetting`

- src/service.rs
Added `SystemStart` (`SERVICE_SYSTEM_START`) and `BootStart` (`SERVICE_BOOT_START`) start types.
This change has been tested locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/113)
> Add `SystemStart` and `BootStart` start types

- CHANGELOG.md
- src/service.rs
Dear maintainers,
The `Service` struct supports modifying the underlying system resource's SID type information through the `Service::set_config_service_sid_info` method. However, there is currently no way to easily retrieve the value from the service manager, for example to check if a call to `set_config_service_sid_info` actually worked.
This PR therefore adds a new small `Service::get_config_service_sid_info` method that does just that. Also, some other minor bonus changes are included.
Cheers,
Paul.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/112)
> Implement new Service method to retrieve its SID type info

- Cargo.toml
- src/service.rs
- src/service_manager.rs
This adds some of the ALL_ACCESS flags + exposes the raw service handle. I'm personally using this for [SetServiceObjectSecurity](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-setserviceobjectsecurity). 
One could expose a more Rust-like `set_service_object_security()` call, though it could become fairly complex. I'm hesitant to try to do that right away before the library is based off of the official Windows crates.
Thoughts?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/115)
> Add some missing flags and expose service handle

- CHANGELOG.md
- src/lib.rs
- src/service.rs
For the upcoming `0.7.0` release we have a lot of breaking changes due to adding variants to enums. Lots of these enums are probably still not exhaustive. To mitigate having to make breaking changes for small stuff in the future, I mark them as `#[non_exhaustive]`. If you think any of these actually are fully exhaustive now, and/or if you think an addition to one of them actually should be a breaking change, then please give that as feedback.
I want this merged before the `0.7.0` release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/124)
> Mark lots of enums `#[non_exhaustive]`

- CHANGELOG.md
- Cargo.toml
Lots of stuff has happened and a full year has passed since 0.6.0. It's about time we get with the times. Here I prepare for releasing 0.7.0. It's a breaking release because we upgrade `windows-sys`
I want #124 merged before we go ahead with this release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/125)
> Prepare to release 0.7.0

- src/service.rs
I don't know if we should provide all combination flags like `GENERIC_READ` listed in https://learn.microsoft.com/en-us/windows/win32/services/service-security-and-access-rights#access-rights-for-a-service, but at least we need to have `READ_CONTROL`, `WRITE_DAC`, `WRITE_OWNER` for modifying security descriptors, this is often used in updater services for preventing UAC prompts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/129)
> Add missing standard access rights for `ServiceAccess`

- .github/workflows/build-and-test.yml
- CHANGELOG.md
- Cargo.toml
- src/sc_handle.rs
- src/service.rs
- src/service_control_handler.rs
- src/service_manager.rs
This updates the windows-sys version to 0.59.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/windows-service-rs/133)
> Bump windows-sys version to 0.59
